"""Self-contained Swing-style read-only GoldScalpTrader secondary visual floor.

The browser is a presentation-only localhost projection of the same normalized
facts used by the primary terminal. It has no BUY/SELL/MODIFY/CLOSE controls,
no Risk/Gate recomputation and no MT5 writer authority.
"""

HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GoldScalpTraderAI · Visual Floor</title>
<style>
:root{color-scheme:dark;--bg:#020d17;--panel:#032131;--line:#16b9db;--cyan:#05ecf4;--gold:#ffdc67;--text:#e9efff;--muted:#a4bcd1;--green:#00e4ba;--red:#ff5364;--amber:#ffd755;--purple:#c98cff}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}body{background:radial-gradient(ellipse at 50% 35%,#07283b,#010a12 80%);color:var(--text);font:13px/1.28 "Segoe UI",Arial,sans-serif}main{padding:7px;display:grid;gap:6px;grid-template-rows:92px 80px minmax(430px,1fr) 145px 112px 21px;height:100vh;min-height:0}h1,h2,h3,p{margin:0}h1{font-size:clamp(29px,2.35vw,46px);line-height:1.02;white-space:nowrap;letter-spacing:-1px;color:var(--gold);text-shadow:0 2px 3px #000}h2{font-size:13px;line-height:22px;letter-spacing:.25px;color:var(--cyan);border-bottom:1px solid #16708b;margin:0 0 4px;padding:0 7px;background:linear-gradient(90deg,#07314988,transparent);white-space:nowrap}.green{color:var(--green)!important}.red{color:var(--red)!important}.amber{color:var(--amber)!important}.cyan{color:var(--cyan)!important}.gold{color:var(--gold)!important}.purple{color:var(--purple)!important}.muted{color:var(--muted)!important}
header,.panel,.metric,.priceCluster,.clockCard,.modeCard,.foot{border:1px solid var(--line);border-radius:7px;box-shadow:inset 0 0 0 3px #00101a,inset 0 0 15px #05729338,0 0 5px #00b5e34a;background:linear-gradient(115deg,#042536,#011421 75%)}header{display:grid;grid-template-columns:34% 32% 34%;align-items:center;padding:5px 9px;min-width:0}.brand{display:flex;align-items:center;gap:12px;min-width:0}.robot{width:76px;height:76px;flex:0 0 76px;filter:drop-shadow(0 0 5px #00ccff)}.robot svg{width:100%;height:100%}.tagline{color:var(--cyan);font-size:clamp(9px,.72vw,14px);font-weight:700;letter-spacing:.3px;margin-top:4px}.invocation{text-align:center;position:relative;padding:0 10px}.arabic{font:27px/1.35 "Segoe UI",serif;color:var(--gold)}.meaning{font-size:11px;color:var(--gold)}.urdu{font-family:"Nirmala UI","Segoe UI",sans-serif}.invocation .urdu{color:var(--gold);font-size:13px;margin-top:2px}.headerRight{display:grid;grid-template-columns:1.7fr 1.05fr 1.05fr;gap:7px;align-items:stretch;padding-left:10px}.motto{align-self:center;text-align:center;font:italic bold clamp(16px,1.1vw,22px)/1.14 Georgia,serif;color:var(--gold)}.motto .urdu{font:15px/1.4 "Nirmala UI","Segoe UI",sans-serif;margin-top:4px}.clockCard,.modeCard{padding:5px 7px;display:flex;flex-direction:column;justify-content:center;text-align:center;min-width:0}.clock{color:var(--cyan);font-size:clamp(18px,1.35vw,27px);font-weight:750;white-space:nowrap}.tiny{font-size:10px;color:var(--muted)}
.marketStrip{display:grid;grid-template-columns:15.5fr 11.5fr 39fr 17fr 17fr;gap:6px;min-width:0}.metric{padding:7px 11px;display:flex;flex-direction:column;justify-content:center;min-width:0}.label{color:var(--cyan);font-size:12px;font-weight:650;line-height:1.1}.value{font-size:24px;line-height:1.15;font-weight:750;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.metric small{font-size:11px;color:var(--text)}#symbol{font-size:28px;color:var(--gold)}.priceCluster{display:grid;grid-template-columns:2.35fr .9fr .9fr .7fr;align-items:center;padding:6px}.priceCluster .cell{padding:0 10px;border-right:1px solid #1b6d87;min-width:0}.priceCluster .cell:last-child{border:0}.priceCluster .major .value{font-size:41px;color:var(--green);letter-spacing:1px}.priceCluster .label{font-size:11px}.priceCluster .value{font-size:18px;font-weight:750}progress{accent-color:#04c9ee;height:7px;width:100%;border:0;display:block;margin-top:6px}#bot{font-size:23px}
.hero{display:grid;grid-template-columns:15.5fr 50fr 34fr;gap:6px;min-height:0}.stack{display:grid;gap:6px;min-height:0;min-width:0}.leftStack{grid-template-rows:1fr .9fr .9fr 1fr}.rightStack{grid-template-rows:1.15fr .95fr .85fr 1.25fr}.panel{padding:4px 5px;min-width:0;min-height:0;overflow:hidden}.kv{display:flex;justify-content:space-between;gap:8px;border-bottom:1px solid #12445a;padding:4px 6px;min-width:0}.kv:last-child{border:0}.kv>span:last-child{text-align:right;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.leftStack .kv{font-size:12px}.reason{font-size:11px;line-height:1.35;margin:4px 7px;color:#d4dff1;overflow-wrap:anywhere}.signalLine{display:flex;align-items:center;justify-content:space-between;padding:0 10px;gap:10px}.signal{font-size:31px;font-weight:780;line-height:1.2}.signalLine .urdu{font-size:21px;color:var(--gold);text-align:right}.scores{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;margin:4px}.score{border:1px solid var(--cyan);border-radius:5px;text-align:center;padding:4px 2px;box-shadow:inset 0 0 8px #03b9d625}.score:nth-child(2){border-color:var(--red)}.score:nth-child(4){border-color:var(--purple)}.score span{font-size:10px;display:block;color:var(--text)}.score b{font-size:20px;color:var(--cyan)}.score:nth-child(2) b{color:var(--red)}.score:nth-child(4) b{color:var(--purple)}.blocker.active{border-color:var(--red);box-shadow:inset 0 0 0 3px #130e18,0 0 6px #ff354a55}.blocker.active h2{color:var(--red)}
.chartPanel{display:flex;flex-direction:column;position:relative}.chartHead{flex:0 0 auto}.chartTools{display:flex;justify-content:space-between;gap:8px;padding:0 5px 4px}.tabs,.toolbar{display:flex;gap:6px;flex-wrap:wrap}button{background:linear-gradient(#073249,#031825);border:1px solid #1885a5;border-radius:5px;color:var(--text);padding:5px 12px;font:inherit;cursor:pointer}button[aria-selected="true"],button.active{color:var(--cyan);border-color:var(--cyan);box-shadow:inset 0 0 10px #00e7d733}button:focus-visible{outline:2px solid var(--gold)}.toolbar button{padding:5px 9px;font-size:11px}.ohlc{padding:4px 8px 2px;font-size:11px;font-variant-numeric:tabular-nums;min-height:20px}.chartWrap{flex:1;min-height:160px;position:relative;margin:0 4px;background:repeating-linear-gradient(90deg,transparent,transparent 49px,#05638913 50px),repeating-linear-gradient(0deg,transparent,transparent 49px,#05638913 50px),linear-gradient(#021926,#00121d)}canvas{width:100%;height:100%;display:block}.chartEmpty{position:absolute;inset:0;display:grid;place-items:center;color:var(--muted);pointer-events:none}.legend{display:flex;flex-wrap:wrap;gap:2px 9px;font-size:9px;color:var(--muted);padding:3px 6px}.planGrid{display:grid;grid-template-columns:1fr 1fr;gap:0 10px}.planGrid .kv{font-size:11px;padding:3px 4px}.strategyMini{font-size:10px}.strategyMini .row{display:grid;grid-template-columns:1.8fr 1.2fr 1fr .65fr;gap:4px;padding:2px 5px;border-bottom:1px solid #123e52}.strategyMini .row:last-child{border:0}.strategyMini .active{color:var(--gold);font-weight:700}
.bottom{display:grid;grid-template-columns:22fr 31fr 47fr;gap:6px;min-height:0}.riskGrid{display:grid;grid-template-columns:1fr 1fr;gap:0 8px}.riskGrid .kv{font-size:10px;padding:2px 4px}.strategyTable{width:100%;border-collapse:collapse;font-size:9px}.strategyTable th{font-size:9px;color:var(--muted);text-align:left;font-weight:500;border-bottom:1px solid #16718b;padding:2px 3px}.strategyTable td{padding:2px 3px;border-bottom:1px solid #11435a}.strategyTable tbody tr:last-child td{border:0}.openTrade{height:calc(100% - 26px);display:grid;place-items:center}.empty{text-align:center;font-size:18px}.empty b{display:block;color:var(--cyan);font-size:25px}.openGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;width:100%}.openGrid .kv{display:block;font-size:10px;border:0}.openGrid .kv span{display:block;text-align:left}
.secondary{display:grid;grid-template-columns:22fr 17fr 17fr 13fr 17fr 14fr;gap:6px;min-height:0}.secondary h2{font-size:10px;line-height:18px}.secondary .kv,.secondary .reason{font-size:9px;padding:2px 4px}.activityBoxes{display:grid;grid-template-columns:repeat(4,1fr);gap:3px}.mini{text-align:center;border-right:1px solid #12445a}.mini:last-child{border:0}.mini b{display:block;font-size:16px}.recent{width:100%;border-collapse:collapse;font-size:8px}.recent th,.recent td{padding:1px 2px;border-bottom:1px solid #12445a;text-align:left}.motivation{display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;color:var(--gold);font:italic bold 13px/1.2 Georgia,serif}.motivation .urdu{font-size:14px;margin-top:5px}.foot{display:flex;align-items:center;justify-content:space-between;padding:2px 8px;font-size:9px;gap:8px;color:var(--muted)}.offline{position:fixed;left:20%;right:20%;top:105px;z-index:20;padding:10px;border:1px solid var(--amber);background:#302719;color:var(--gold);border-radius:5px;text-align:center;display:none}.offline.show{display:block}.dimmed{filter:saturate(.45);opacity:.67}
@media(max-height:850px){main{grid-template-rows:76px 65px minmax(330px,1fr) 120px 96px 18px}.robot{width:58px;height:58px;flex-basis:58px}.arabic{font-size:22px}.value{font-size:19px}.priceCluster .major .value{font-size:31px}.signal{font-size:25px}}
@media(max-width:1350px){header{grid-template-columns:46% 54%}.invocation{display:none}.headerRight{grid-column:2}.hero{grid-template-columns:19fr 48fr 33fr}.secondary{grid-template-columns:repeat(3,1fr)}.secondary .panel:nth-child(n+4){display:none}}
</style></head><body>
<div id="offline" class="offline">Waiting for dashboard snapshot…</div>
<main id="main">
<header><div class="brand"><div class="robot"><svg viewBox="0 0 100 100" aria-hidden="true"><defs><linearGradient id="rg" x1="0" x2="1"><stop stop-color="#0be7ff"/><stop offset="1" stop-color="#056b87"/></linearGradient></defs><rect x="20" y="26" width="60" height="50" rx="16" fill="#02131d" stroke="url(#rg)" stroke-width="4"/><path d="M50 12v14M42 12h16" stroke="#ffdc67" stroke-width="4" stroke-linecap="round"/><circle cx="38" cy="48" r="6" fill="#00e4ba"/><circle cx="62" cy="48" r="6" fill="#00e4ba"/><path d="M36 63q14 9 28 0" fill="none" stroke="#05ecf4" stroke-width="4" stroke-linecap="round"/><path d="M20 47H10M80 47h10M31 80v8M69 80v8" stroke="#16b9db" stroke-width="5" stroke-linecap="round"/></svg></div><div><h1>GoldScalpTraderAI</h1><div class="tagline">M5 PRECISION FLOOR · M1 TIMING · 1 ACTIVE + 5 SHADOW · GOVERNED EXECUTION</div></div></div><div class="invocation"><div class="arabic">بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ</div><div class="meaning">In the name of Allah, the Most Gracious, the Most Merciful.</div><div class="urdu">نظم و ضبط کے ساتھ مسلسل بہتری</div></div><div class="headerRight"><div class="motto">“Fast Decisions,<br>Governed Risk”<div class="urdu">تیز فیصلہ · محفوظ عمل</div></div><div class="clockCard"><div id="date" class="tiny">—</div><div id="clock" class="clock">—</div><div class="tiny">PKT</div></div><div class="modeCard"><div class="tiny">MODE / ROLE</div><b id="mode" class="green">DEMO</b><div class="tiny">SECONDARY · READ ONLY</div></div></div></header>
<section class="marketStrip"><div class="metric"><div class="label">🪙 SYMBOL</div><div id="symbol" class="value">—</div><small>Gold vs US Dollar</small></div><div class="metric"><div class="label">🌍 MARKET</div><div id="market" class="value">—</div><small>Session: <span id="session">—</span></small></div><div class="priceCluster"><div class="cell major"><div class="label">LIVE PRICE</div><div id="mid" class="value">—</div><small id="quoteAge">Feed —</small></div><div class="cell"><div class="label">Bid</div><div id="bid" class="value green">—</div></div><div class="cell"><div class="label">Ask</div><div id="ask" class="value red">—</div></div><div class="cell"><div class="label">Spread</div><div id="spread" class="value">—</div></div></div><div class="metric"><div class="label">⏱ CANDLE CLOSE (M5)</div><div id="countdown" class="value">—</div><progress id="candleProgress" max="300" value="0"></progress></div><div class="metric"><div class="label">🤖 BOT STATUS</div><div id="bot" class="value cyan">STARTING</div><small id="systemTop">Dashboard alive</small></div></section>
<section class="hero"><div class="stack leftStack"><div class="panel"><h2>📊 MARKET ANALYSIS / مارکیٹ</h2><div id="indicatorRows"></div></div><div class="panel"><h2>⬆ TREND DIRECTION</h2><div id="structureRows"></div></div><div class="panel"><h2>🌍 SESSION / NEWS</h2><div class="kv"><span>Hard Session</span><span id="hardSession">—</span></div><div class="kv"><span>Schedule</span><span id="schedule">—</span></div><div class="kv"><span>News</span><span id="news">—</span></div><div id="sessionReason" class="reason muted">—</div></div><div class="panel"><h2>🧬 TIMING INTELLIGENCE / وقت</h2><div id="timingRows"></div></div></div>
<div class="panel chartPanel"><div class="chartHead"><h2>📉 CHART — COMPLETED CANDLES ONLY</h2></div><div class="chartTools"><div class="tabs" id="tabs"><button data-tf="M1">M1</button><button data-tf="M5" aria-selected="true">M5</button><button data-tf="M15">M15</button><button data-tf="H1">H1</button><button data-tf="H4">H4</button></div><div class="toolbar"><button id="indBtn">Indicators ON</button><button id="drawBtn">Drawings OFF</button><button id="settingsBtn">Settings OFF</button><button id="bars">Bars 60</button></div></div><div id="ohlc" class="ohlc">O — H — L — C —</div><div class="chartWrap"><canvas id="chart"></canvas><div id="chartEmpty" class="chartEmpty">Waiting for completed candles…</div></div><div id="legend" class="legend">EMA20 · EMA50 · no forming candle · presentation only</div></div>
<div class="stack rightStack"><div class="panel"><h2>🎯 CURRENT SIGNAL / DECISION / موجودہ فیصلہ</h2><div class="signalLine"><div id="action" class="signal amber">WAIT</div><div id="actionUrdu" class="urdu signalUrdu">انتظار</div></div><div class="scores"><div class="score"><span>BUY</span><b id="buyScore">—</b></div><div class="score"><span>SELL</span><b id="sellScore">—</b></div><div class="score"><span>LEAD</span><b id="leadScore">—</b></div><div class="score"><span>COVERAGE</span><b id="coverage">—</b></div></div><div id="reason" class="reason">—</div></div><div class="panel"><h2>📋 TRADE PLAN / تجارتی منصوبہ <span id="planState" class="gold">WAITING</span></h2><div id="plan" class="planGrid"></div></div><div id="blockerPanel" class="panel blocker"><h2>🚦 CURRENT BLOCKER / GATE</h2><div class="kv"><span>Gate</span><span id="gate">—</span></div><div id="blockerReason" class="reason">—</div></div><div class="panel"><h2>👥 STRATEGY / SETUP BOARD · 1 ACTIVE + 5 SHADOW</h2><div id="strategyMini" class="strategyMini"></div></div></div></section>
<section class="bottom"><div class="panel"><h2>🛡️ RISK & ACCOUNT / رسک</h2><div id="risk" class="riskGrid"></div></div><div class="panel"><h2>🧪 STRATEGY / SETUP BOARD</h2><table class="strategyTable"><thead><tr><th>Family</th><th>Mode</th><th>Qual</th><th>Dir</th><th>Score</th></tr></thead><tbody id="strategyBody"></tbody></table></div><div class="panel"><h2>💼 OPEN / MANAGED TRADE / کھلی پوزیشن</h2><div id="openTrade" class="openTrade"><div class="empty"><b>▤</b>No open managed trade<div class="urdu">کوئی کھلی پوزیشن نہیں</div></div></div></div></section>
<section class="secondary"><div class="panel"><h2>📈 TODAY / ACTIVITY</h2><div class="activityBoxes"><div class="mini">Positions<b id="positions">—</b></div><div class="mini">Shadow<b id="shadowCount">—</b></div><div class="mini">Mode<b>DEMO</b></div><div class="mini">Writer<b>SAFE</b></div></div><div id="activity" class="reason">—</div></div><div class="panel"><h2>🧠 LEARNING & DISCOVERY</h2><div id="learning" class="reason">—</div><div class="kv"><span>Discovery</span><span id="discovery">ACTIVE</span></div><div class="reason muted">Bounded research only · no runtime activation</div></div><div class="panel"><h2>✅ RECENT VERIFIED CLOSES</h2><div class="reason muted">No verified-close table is projected in the current snapshot; no result is fabricated.</div></div><div class="panel"><h2>⚙️ EXECUTION & CONTROLLER</h2><div id="execution" class="reason">—</div></div><div class="panel"><h2>🩺 SYSTEM & DATA</h2><div id="system" class="reason">—</div><div class="reason muted">no broker controls · browser read-only</div></div><div class="panel motivation">Discipline Before Speed<div class="urdu">پہلے نظم و ضبط، پھر رفتار</div></div></section>
<div class="foot"><span>Terminal = PRIMARY · Browser = SECONDARY · localhost read-only · no BUY/SELL/MODIFY/CLOSE controls</span><span id="freshness">Snapshot —</span></div>
</main>
<script>
'use strict';
let snapshot=null,currentTf='M5',indicatorsOn=true,drawingsOn=false,settingsOpen=false,bars=60,lastGenerated=null;
const $=id=>document.getElementById(id); const n=(v,d=3)=>v===null||v===undefined?'—':Number(v).toFixed(d); const pct=v=>v===null||v===undefined?'—':(Number(v)*100).toFixed(1)+'%';
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cls(v){v=String(v??'').toUpperCase(); if(/OPEN|READY|PASS|BUY|HEALTHY|ACTIVE|LIVE|CLEAR/.test(v))return'green'; if(/SELL|BLOCK|FAIL|ERROR|DEGRADED|FAULT/.test(v))return'red'; if(/WAIT|UNKNOWN|CLOSED|PRE_CLOSE|IDLE|NOT_EVALUATED/.test(v))return'amber'; return'cyan'}
function set(id,v,c){const e=$(id); if(!e)return;e.textContent=v??'—';e.className=(e.className.split(' ').filter(x=>!['green','red','amber','cyan','gold','purple'].includes(x)).join(' ')+' '+(c||'')).trim()}
function kv(k,v,c=''){return `<div class="kv"><span>${esc(k)}</span><span class="${c}">${esc(v)}</span></div>`}
function actionUrdu(a){a=String(a||'WAIT').toUpperCase();return a.includes('BUY')?'خرید':a.includes('SELL')?'فروخت':'انتظار'}
function pretty(s){return String(s??'—').replaceAll('_',' ')}
function clock(){const d=new Date();const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Karachi',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(d);const q=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Karachi',day:'2-digit',month:'short',year:'numeric'}).format(d);set('clock',p,'cyan');set('date',q);if(lastGenerated){const age=Math.max(0,(Date.now()-new Date(lastGenerated).getTime())/1000);set('freshness',`Snapshot ${age.toFixed(1)}s ago`,age>6?'amber':'green')}} setInterval(clock,250);clock();
function render(s,online=true,message='LIVE'){
 snapshot=s; lastGenerated=s.generated_at_utc; const m=s.market||{},ss=s.session||{},d=s.decision||{},t=s.timing||{},p=s.plan||{},r=s.risk||{};
 set('symbol',m.symbol,'gold');set('market',m.state,cls(m.state));set('session',ss.soft_session||ss.hard_state);set('hardSession',ss.hard_state,cls(ss.hard_state));set('schedule',ss.schedule_verified?'VERIFIED':'UNKNOWN',ss.schedule_verified?'green':'amber');set('news',ss.news_health,cls(ss.news_health));set('sessionReason',ss.reason||ss.source||'—');
 const mid=(m.bid!=null&&m.ask!=null)?(Number(m.bid)+Number(m.ask))/2:null;set('mid',n(mid),'green');set('bid',n(m.bid),'green');set('ask',n(m.ask),'red');set('spread',n(m.spread));set('bot',d.bot_status,cls(d.bot_status));set('systemTop',d.system||'Dashboard alive');
 const remaining=calcCountdown();set('countdown',remaining.text);$('candleProgress').value=remaining.elapsed;
 const inds=s.indicators||{},i5=inds.M5||{};$('indicatorRows').innerHTML=kv('EMA20',n(i5.ema20),'cyan')+kv('EMA50',n(i5.ema50),'cyan')+kv('RSI',n(i5.rsi,1),'gold')+kv('ATR',n(i5.atr,3),'purple')+kv('Flow',pretty(i5.flow));
 const st=s.structure||{};$('structureRows').innerHTML=['H4','H1','M15','M5'].map(tf=>kv(tf,pretty((st[tf]||{}).state),cls((st[tf]||{}).state))).join('');
 $('timingRows').innerHTML=kv('Outcome',pretty(t.outcome),cls(t.outcome))+kv('Profile',t.profile||'—')+kv('Opportunity',pretty(t.opportunity_state))+kv('M5 Age',t.m5_event_age_bars==null?'—':t.m5_event_age_bars+' bars')+kv('M1 Age',t.trigger_age_seconds==null?'—':n(t.trigger_age_seconds,1)+'s');
 set('action',pretty(d.action),cls(d.action));set('actionUrdu',actionUrdu(d.action),'gold');set('buyScore',pct(d.buy_score),'cyan');set('sellScore',pct(d.sell_score),'red');set('leadScore',pct(d.leading_score),'gold');set('coverage',pct(d.coverage),'purple');set('reason','WHY / وجہ: '+(d.reason||'—'));
 set('planState',p.exists?'READY':'WAITING',p.exists?'green':'amber');$('plan').innerHTML=p.exists?(kv('Direction',pretty(p.direction),cls(p.direction))+kv('Entry',n(p.entry))+kv('Stop',n(p.stop),'red')+kv('TP1',n(p.primary),'green')+kv('TP2',n(p.expansion),'cyan')+kv('Gross R',p.gross_r==null?'—':n(p.gross_r,2)+'R','gold')):(kv('Direction','WAIT','amber')+kv('Entry','—')+kv('Stop','—')+kv('TP1','—')+kv('TP2','—')+kv('Gross R','—'));
 set('gate',pretty(d.gate),cls(d.gate));set('blockerReason',d.reason||'No active blocker');$('blockerPanel').classList.toggle('active',/BLOCK|CLOSED|UNKNOWN|FAIL|DEGRADED/.test(String(d.gate)+' '+String(m.state)));
 renderStrategies(s.strategy_board||[]);$('risk').innerHTML=kv('Decision',pretty(r.decision),cls(r.decision))+kv('Profile',pretty(r.profile))+kv('Risk %',r.risk_pct==null?'—':n(r.risk_pct,2)+'%')+kv('Risk $',r.risk_money==null?'—':'$'+n(r.risk_money,2))+kv('Lot',n(r.volume,2))+kv('Balance',m.balance==null?'—':'$'+n(m.balance,2))+kv('Equity',m.equity==null?'—':'$'+n(m.equity,2))+kv('Free Margin',m.free_margin==null?'—':'$'+n(m.free_margin,2));
 renderTrade(s.management);set('positions',s.management?1:0);set('shadowCount',s.shadow_count??(s.shadows||[]).length);set('activity',(s.execution||{}).activity||'—');set('learning',(s.learning||{}).text||'Waiting for verified evidence');set('execution',(s.execution||{}).text||'IDLE');set('system',d.system||'—');
 $('main').classList.toggle('dimmed',!online);$('offline').classList.toggle('show',!online);$('offline').textContent=message||'BOT OFFLINE / SNAPSHOT STALE'; renderChart();clock();
}
function renderStrategies(rows){$('strategyBody').innerHTML=rows.map(x=>`<tr><td>${esc(pretty(x.family))}</td><td class="${String(x.mode).includes('ACTIVE')?'gold':'muted'}">${esc(pretty(x.mode))}</td><td>${esc(pretty(x.qualification))}</td><td class="${cls(x.direction)}">${esc(pretty(x.direction))}</td><td>${esc(pct(x.score))}</td></tr>`).join('');$('strategyMini').innerHTML=rows.map(x=>`<div class="row ${String(x.mode).includes('ACTIVE')?'active':''}"><span>${esc(pretty(x.family))}</span><span>${esc(pretty(x.mode))}</span><span>${esc(pretty(x.qualification))}</span><span>${esc(x.direction||'—')}</span></div>`).join('')}
function renderTrade(t){const e=$('openTrade');if(!t){e.innerHTML='<div class="empty"><b>▤</b>No open managed trade<div class="urdu">کوئی کھلی پوزیشن نہیں</div></div>';return}e.innerHTML=`<div class="openGrid">${kv('Ticket',t.ticket)}${kv('Family',pretty(t.family))}${kv('Direction',pretty(t.direction),cls(t.direction))}${kv('Entry',n(t.entry))}${kv('Stop',n(t.stop),'red')}${kv('TP1',n(t.primary),'green')}${kv('TP2',n(t.expansion),'cyan')}${kv('Volume',n(t.volume,2))}${kv('Manager',pretty(t.manager_action),cls(t.manager_action))}</div>`}
function calcCountdown(){const now=new Date();const sec=now.getUTCMinutes()%5*60+now.getUTCSeconds();return{text:`${String(Math.floor((300-sec)/60)).padStart(2,'0')}:${String((300-sec)%60).padStart(2,'0')}`,elapsed:sec}}
function renderChart(){if(!snapshot)return;const rows=((snapshot.charts||{})[currentTf]||[]).slice(-bars);const canvas=$('chart'),box=canvas.parentElement,rect=box.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(2,Math.floor(rect.width*dpr));canvas.height=Math.max(2,Math.floor(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);$('chartEmpty').style.display=rows.length?'none':'grid';if(!rows.length){set('ohlc','O — H — L — C —');return}const lo=Math.min(...rows.map(x=>Number(x.low))),hi=Math.max(...rows.map(x=>Number(x.high))),range=Math.max(.0001,hi-lo),pad=18;const y=v=>pad+(hi-Number(v))/(range)*(h-pad*2),step=(w-16)/rows.length,cw=Math.max(2,Math.min(10,step*.55));ctx.lineWidth=1;rows.forEach((x,i)=>{const cx=8+i*step+step/2,up=Number(x.close)>=Number(x.open);ctx.strokeStyle=ctx.fillStyle=up?'#00e4ba':'#ff5364';ctx.beginPath();ctx.moveTo(cx,y(x.high));ctx.lineTo(cx,y(x.low));ctx.stroke();const top=Math.min(y(x.open),y(x.close)),bh=Math.max(1,Math.abs(y(x.open)-y(x.close)));ctx.fillRect(cx-cw/2,top,cw,bh)});if(indicatorsOn){drawMA(ctx,rows,20,w,h,lo,hi,'#05ecf4');drawMA(ctx,rows,50,w,h,lo,hi,'#ffdc67')}const last=rows[rows.length-1];set('ohlc',`${currentTf}  O ${n(last.open)}  H ${n(last.high)}  L ${n(last.low)}  C ${n(last.close)}  Vol ${last.tick_volume??'—'}`)}
function drawMA(ctx,rows,p,w,h,lo,hi,color){if(rows.length<p)return;const range=Math.max(.0001,hi-lo),pad=18,step=(w-16)/rows.length,y=v=>pad+(hi-v)/range*(h-pad*2);ctx.strokeStyle=color;ctx.lineWidth=1.2;ctx.beginPath();let started=false;for(let i=p-1;i<rows.length;i++){let sum=0;for(let j=i-p+1;j<=i;j++)sum+=Number(rows[j].close);const cx=8+i*step+step/2,cy=y(sum/p);if(!started){ctx.moveTo(cx,cy);started=true}else ctx.lineTo(cx,cy)}ctx.stroke()}
$('tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-tf]');if(!b)return;currentTf=b.dataset.tf;document.querySelectorAll('#tabs button').forEach(x=>x.setAttribute('aria-selected',String(x===b)));renderChart()});$('indBtn').onclick=()=>{indicatorsOn=!indicatorsOn;$('indBtn').textContent='Indicators '+(indicatorsOn?'ON':'OFF');$('indBtn').classList.toggle('active',indicatorsOn);renderChart()};$('drawBtn').onclick=()=>{drawingsOn=!drawingsOn;$('drawBtn').textContent='Drawings '+(drawingsOn?'ON':'OFF');$('drawBtn').classList.toggle('active',drawingsOn)};$('settingsBtn').onclick=()=>{settingsOpen=!settingsOpen;$('settingsBtn').textContent='Settings '+(settingsOpen?'ON':'OFF');$('settingsBtn').classList.toggle('active',settingsOpen)};$('bars').onclick=()=>{bars=bars===60?120:bars===120?30:60;$('bars').textContent='Bars '+bars;renderChart()};window.addEventListener('resize',renderChart);
async function poll(){try{const r=await fetch("/api/snapshot",{cache:'no-store'}),state=await r.json();if(state.snapshot)render(state.snapshot,Boolean(state.online),state.message);else{$('offline').classList.add('show');$('offline').textContent=state.message||'Waiting for dashboard snapshot…';$('main').classList.add('dimmed')}}catch(e){$('offline').classList.add('show');$('offline').textContent='Dashboard connection unavailable';$('main').classList.add('dimmed')}}setInterval(poll,1000);poll();
</script></body></html>'''

__all__ = ["HTML"]
